### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by valuser** [mottolini/buddypress-xprofile-member-type-field#2]
Hi,

Many Thanks for Plugin.

How does this operate in a multiste installation ?

At the moment I am unable to input member types ?

The field after a value is inserted just keeps returning blank - having begun with a default value 1

Irespective of where the plugin is - Network Activated  or just Activated on the Site (1)  itself.

Cheers,

Val

plugin just downloaded - most up-to-date versions of BP and WP

**Comment by mottolini** [comment]
Never tested in a multisite installation, because I don't have any.
Definitely could be the cause of your issue, even if I don't understand why are you talking about a "default value 1": this field doesn't accept values, it only allows to select one of the defined member types.
How many member types have you defined?

M

**Comment by valuser** [comment]
Thanks for prompt reply

i think its just down to multisite!

Local install

Activate plugin

I am here

http://jsourplace.dev/wp-admin/network/users.php?page=bp-profile-setup

I add a Member Type field.

i see this

![profile_fields_member_type](https://cloud.githubusercontent.com/assets/2312247/11212829/2c82e94a-8d30-11e5-8110-8c1f5d3007c1.jpg)

i click edit

i see this

![profile_fields_add](https://cloud.githubusercontent.com/assets/2312247/11212846/5197608a-8d30-11e5-88be-585c9d24ed34.jpg)

even when i add a field (where 1 was)  say Teacher click save everthing else is saved EXCEPT the member profile field which still comes back as 1 and does not change to Teacher

this comes back
![profile_fields_new](https://cloud.githubusercontent.com/assets/2312247/11212882/8e9f4722-8d30-11e5-9fd8-6af5354ec0b8.jpg)

It just seems to me (fully accepting that i could easily be wrong) that the plugin needs to be configured to allow Network capability.

**Comment by mottolini** [comment]
I already asked you: how many member types have you defined?

When you create the field what do you see in the bottom right?
Look at this picture: if you don't have defined member types you can't assign them...

![img05](https://cloud.githubusercontent.com/assets/891449/11215762/2246ce8e-8d48-11e5-9b79-32d57b2a47e7.png)

**Comment by valuser** [comment]
Sincere apologies - forgive me!

if i had taken the time to read the complete page i would have realised that i needed the plugin. BuddyPress Member Type generator !

Again my bad. Please close this issue.
